language: python
python:
- 3.8
- 3.7
- 3.6
install: true
script: echo "Skipping tests"
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: DaLkgSHFI0USPn3iOMzDy5jchSH9wJAXtWDzX1kvNLH6XY+jby8MtdJcxtQzWeNz72VKr1yUXERsdeitfTXJHiZ3VIDKIik0x/ci8bWzakXRKoMsimS2ucXEfbq+bw8+MrD3WVSJG5UOrO5gI75/VGBWp3lJgAqqI68p/MzAayA35QA6J33uYNI8acNyRZA4vykl/luoiX9ih1GKtiaiv/3telNdwwDRZwh6NJPENuMvnZblMgmgwTjpI4IDkCpUOMtF/7HX9daL6eH7Cc4YVzU1Uc7dLzFx4m6Q0ow7CQ57QDLyFZm/X/cAkGzmuIYCzuwx/eAoFX0B8Q/887tO0q1WalflTrBO9co10DVaNpc0ka6Y8EiqZxtVgvZcpjCj1tX6Dqj3A4e99CnBb7Yiy5IcGqz76LT4iZXFTeB2M84bd5DFV0DUtoA+kCB+sJ/o31fkPAM0M1I5RY8EGzHCIsAfy5kEwuexhW6k0L3pBxxu7PRYzj/yfLYX7Npq8YSQIO/20PnK/taS6negYHucMuAfTXUOzC0Bx62IFkq3tnj/trYHbvsErcRc9Jg79vECAM6c4X0+VY1G5hq/5SLi+9Zhe2lfHUjSFefg2KDITTMkNCBQBMpkK2mNM/MBo5/hVphDaUyIyNQW4CfhQady1IWIerDzvTSzFZAt7p/WNyk=
  on:
    tags: true
    all_branches: true
    repo: grahamwetzler/smart-meter-texas
    python: 3.8
