language: python
python:
- 3.8
- 3.7
- 3.6
install: true
script: echo "Skipping tests"
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: mymmU/EEal3wd/h5VTlArqUwZUmn1eRi4i8oQbRvxOojA6lY2MgXN0H+JBdBZRePNBCrkytoTiJ65CN4htgFqHds/alLnOCmkuNVbcRzSxYR44fJwLd43rqrDUsqPD+ZXuRvUq9BgQReENpbqg2IUVa64ZVpIuNs2q1UuL+C5UQDykBkONyy2cU+QiIAeUrGclzrUoho3WYlfWRN9D4iG3OcGJ2XmxjyL5ar9QbVlx76pk0XoYb7kKTE1MsBfnAGqJusNnuZ4AUHfe/P7Ti+sNuAY6QsH0SPzHrmZUl0rEUaUGN6FSFo65V9VRbUC3DHW8V+CDLhSxEQrda+e7S+OLQTOVWV+eDHbQsEGMZUR3Wp5xwiPzYJcJXG9ouBDE3Q4r/iC/URUqr1N19BTJ+5IaYnhOr61/DWV4kRsuSRu/66z4b1dx52oA+nH9T3CPhTw7qPGC6wtjg8fZkk8ykifBvnneWLsOVKiiSy7C0qLIiUUH4xP/98CNL0l0YXhGd6IkfXDGLduFr8Zk2TW5xwq1Qw63Fs7RbyvgIe9Q5QfJp4c2gOMSqdd7VQmtDus7k6HuDgHrmyH7BLypbUFni/HuKYMMV9Nof6oTFML2SPhfYBSnUouTidyKDS62TlU3FxP4RnKF1iCPlnf3CX/iBwFgpRTXAQwLUVRpn6j7eTMeU=
  on:
    tags: true
    all_branches: true
    repo: grahamwetzler/smart-meter-texas
    python: 3.8
