language: python
python:
- 3.8
- 3.7
- 3.6
install: true
script: echo "Skipping tests"
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: grahamwetzler
  password:
    secure: Mxjh6Z429yXCYqwoVfcgeWNbx9CkYS7jMej2RdgQGs/RKYhXOKKNXizk+j+bCHxN51Y66+wROxnrvwpmCMZPOwA6c6a2hDLyMQYCbpsgATTmyUXR5jFwoksmNuoB0MrJe0Qlh5SI1DgmhDt0G5UR65zY7xSLUVQFyXNYr2DwL2CJFdTw3R19XYCy+kIo8FPS7E52qkQHYHyG9Rv58S0wapSQauUOddGZOy35NqSBSlLG7/eEhyK0oGTw0NQZpH3PD3pfPhUWf0dGgnh3vqakPz7fNYQUm/y1EmuMET0XbTqipk1y2P+tlOa2o9pdeD2rO90cn6TdseeG4g8xrupkPUO4dEw7bAm5oUeTyiwUH+Fx1HeqnSFPpIjoK8tU4B6YaUStqWQ1hsbIVmWBi+UlxJ+zfk5fD+cvVztAwf9aRgWogKHKFjHHj47XMwGGRXWo+9qgNwEMA3qsam6mXoDLn4/xsExFmIAuWAtBFhmkmG5rVnjqeRRzYaS4lWRc2ed976yA3iuA8lW5U+zcP68w6bpDujfsu2nh9hBfd9SNdQgRWSQj8edPy9gBN74R2n6GKY1T9BgivdZfShS2wd3ahs/GACEZFX/0EqsaAwUQ+qYQTcNUxHDkFApVYPZLBra10LMa74BBswKKH82UNsbdSTR2kBzbNDVvA+rAeyfAl8M=
  on:
    tags: true
    repo: grahamwetzler/smart_meter_texas
    python: 3.8
