name: CI
on:
  - push
  - pull_request


jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        
      - name: python-isort
        uses: isort/isort-action@v0.1.0
        with:
          configuration: --check-only --diff --profile black

      - name: python-black
        uses: lgeiger/black-action@4379f39aa4b6a3bb1cceb46a7665b9c26647d82d
        with:
          args: ". --check"
